#!/bin/sh
exec 2>&1
sv down agetty-tty2
if [ ! -f /run/ly_switched ]; then
	chvt 2
	touch /run/ly_switched
fi
export TERM=linux
export LANG=c.UTF-8
stty sane < /dev/tty2
exec setsid sh -c '/usr/bin/ly < /dev/tty2 > /dev/tty2 2>&1'
